#                        Copyright (c) 1988 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: Makefile,v 1.3 88/07/21 14:07:38 sau Exp $
#	$Source: /tmp/mgrsrc/icon/grey/RCS/Makefile,v $

#	grey icons for mgr
START=.
ICONS= \
	0 100 15 20 25 33 50 67 75 80 85

all clean clobber cpio:

list:
	@for i in README Makefile $(ICONS); do \
		echo "$(START)/$$i"; \
	 done
