#!/bin/sh
#                        Copyright (c) 1987 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: font,v 4.1 88/06/21 14:01:30 bianchi Exp $
#	$Source: /tmp/mgrsrc/demo/sh/RCS/font,v $

#	change to a new font

FONT="F"
ESC=""
ECHO=/bin/echo

if /bin/test $TERM != mgr
then
   $ECHO "$0 only works on mgr terminals"
   exit 1
fi

$ECHO -n "$ESC$1$FONT"
