#!/bin/sh
#                        Copyright (c) 1987 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: more,v 4.1 88/06/21 14:01:35 bianchi Exp $
#	$Source: /tmp/mgrsrc/demo/sh/RCS/more,v $

if [ $TERM = mgr ]
then
	eval "`set_termcap -b`" 
fi
exec /usr/ucb/more $*
