#                        Copyright (c) 1988 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: Makefile,v 1.2 88/07/21 14:06:17 sau Exp $
#	$Source: /tmp/mgrsrc/icon/mouse/RCS/Makefile,v $

#	grey icons for mgr
START=.
ICONS= \
	hhand0 hhand1 hhand10 hhand11 hhand2 hhand3 \
	hhand4 hhand5 hhand6 hhand7 hhand8 hhand9 \
	mhand0 mhand1 mhand10 mhand11 mhand2 mhand3 \
	mhand4 mhand5 mhand6 mhand7 mhand8 mhand9 \
	mhhand0 mhhand1 mhhand10 mhhand11 mhhand2 mhhand3 \
	mhhand4 mhhand5 mhhand6 mhhand7 mhhand8 mhhand9 \
	mickface mmhand0 mmhand1 mmhand10 mmhand11 mmhand2 \
	mmhand3 mmhand4 mmhand5 mmhand6 mmhand7 mmhand8 \
	mmhand9

all clean clobber cpio:

list:
	@for i in README Makefile $(ICONS); do \
		echo "$(START)/$$i"; \
	 done
