#                        Copyright (c) 1988 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: Makefile,v 1.2 88/07/21 14:04:42 sau Exp $
#	$Source: /tmp/mgrsrc/icon/eye/RCS/Makefile,v $

#	icons for mgr logo
START=.
ICONS= \
	mgrlogo_1 mgrlogo_2 mgrlogo_3 mgrlogo_4 \
	mgrlogo_5 mgrlogo_6 mgrlogo_7 mgrlogo_8

all clean clobber cpio:

list:
	@for i in Makefile $(ICONS); do \
		echo "$(START)/$$i"; \
	 done
